services:

  # ===========================
  # KAFKA
  # ===========================
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - space-network


  # ===========================
  # HDFS NAMENODE
  # ===========================
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode

    ports:
      - "9870:9870"
      - "9000:9000"

    environment:
      CLUSTER_NAME: space-datalake
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_client_use_datanode_hostname: "true"
      HDFS_CONF_dfs_permissions_enabled: "false"

    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./data:/data
      - ./spark:/spark

    networks:
      - space-network


  # ===========================
  # HDFS DATANODE
  # ===========================
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode

    ports:
      - "9864:9864"
      - "9866:9866"

    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_datanode_use_datanode_hostname: "true"
      HDFS_CONF_dfs_client_use_datanode_hostname: "true"
      HDFS_CONF_dfs_datanode_hostname: datanode
      HDFS_CONF_dfs_permissions_enabled: "false"

    volumes:
      - datanode-data:/hadoop/dfs/data

    depends_on:
      - namenode

    networks:
      - space-network


  # ===========================
  # SPARK MASTER
  # ===========================
  spark-master:
    image: bitnamilegacy/spark:3.5
    container_name: spark-master
    hostname: spark-master
    user: "0:0"

    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077

      USER: root
      HOME: /root
      HADOOP_USER_NAME: root

    ports:
      - "7077:7077"
      - "8080:8080"

    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/data

    depends_on:
      - kafka
      - namenode

    networks:
      - space-network


  # ===========================
  # SPARK WORKER
  # ===========================
  spark-worker:
    image: bitnamilegacy/spark:3.5
    container_name: spark-worker
    hostname: spark-worker
    user: "0:0"

    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077

      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2

      USER: root
      HOME: /root
      HADOOP_USER_NAME: root

    depends_on:
      - spark-master

    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/data

    networks:
      - space-network


  # ===========================
  # AIRFLOW
  # ===========================
  airflow:
    image: apache/airflow:2.10.5
    container_name: airflow
    hostname: airflow

    command: standalone

    ports:
      - "8088:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      HADOOP_USER_NAME: root

      # Installe le SDK Docker Python dans Airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "docker"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark:/opt/airflow/spark
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

      # Permet à Airflow de piloter les conteneurs Docker
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - kafka
      - namenode
      - spark-master

    networks:
      - space-network


  # ===========================
  # STREAMLIT APPLICATION
  # ===========================
  streamlit:
    build:
      context: .
      dockerfile: app/Dockerfile

    container_name: streamlit
    hostname: streamlit

    user: "0:0"

    ports:
      - "8501:8501"

    environment:
      USER: root
      HOME: /root
      HADOOP_USER_NAME: root

      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
      PATH: /usr/lib/jvm/java-21-openjdk-amd64/bin:/usr/local/bin:/usr/bin:/bin

    volumes:
      - ./app:/app
      - ./spark:/opt/spark-apps

    depends_on:
      - namenode
      - datanode
      - spark-master

    networks:
      - space-network


# ===========================
# NETWORK
# ===========================
networks:
  space-network:
    driver: bridge


# ===========================
# VOLUMES
# ===========================
volumes:
  namenode-data:
  datanode-data: